export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE'
export const SET_INIT_CURRENT_LOCALE = 'SET_INIT_CURRENT_LOCALE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT'

export const SET_LOGIN = 'SET_TOKEN'
export const SET_LOGOUT = 'SET_LOGOUT'

export const SET_SOCKET = 'SET_SOCKET'
export const COMMIT_AUTHENTICATED = 'COMMIT_AUTHENTICATED'
